# Name of the workflow
name: Hello World Workflow

# event that triggers the workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, staging ]
# jobs to be run as part of the workflow
jobs:
  greet:
    # type of runner to execute the job
    runs-on: ubuntu-latest

    # steps to be executed in the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World!"