# Name of the workflow
name: Hello World Workflow

# event that triggers the workflow
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, staging ]
# jobs to be run as part of the workflow
jobs:
  greet:
    # type of runner to execute the job
    runs-on: ubuntu-latest

    # steps to be executed in the job
    steps:
    # run a single line command
      - name: Hello
        run: echo "Hello, World!"